name = 's1'

[train]
	epochs = 20
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.7 			# Learning rate step gamma
	save_model = true
	save_log = true
	
	log_interval = 100		# pring while n-th batch
	gpu = true

	ReLU_estimation = 'TD' # TD: train distribution, IP: interval propagation, VS: verification sampling
	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]	

[heuristic]

[verify]
	time = 1200
	memory = '8G'
	debug = false
	save_log = true
