name = 's2'

[train]
	epochs = 100
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.95 			# Learning rate decay
	save_model = true
	save_log = true
	save_intermediate = true
	log_interval = 100		# pring while n-th batch
	gpu = true
	amp = false

	ReLU_estimation = 'TD' # TD: train distribution, IP: interval propagation, VS: verification sampling
	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]	

[verify]
	time = 600
	memory = '8G'
	property = 0
	epsilon = 0.02
	save_log = true
	target_model = 'best'
	verifier = 'neurify'
