name = 's3.v1'

[train]
	epochs = 20
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.95 			# Learning rate decay
	save_model = true
	save_log = true
	save_intermediate = true
	log_interval = 100		# pring while n-th batch
	gpu = true
	amp = false

	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]	

[verify]
	time = 600
	memory = '16G'
	save_log = false
	debug = true
	
	target_model = 'top 1 test accuracy'
	verifier = 'DNNVWB:neurify'
