name = 's3'

[train]
	epochs = 20
	batch_size = 16
	test_batch_size = 16
	lr = 1e-3							# learning rate
	gamma = 0.99 						# Learning rate decay
	save_model = true
	save_intermediate = true
	save_log = false
	log_interval = 10					# Stable ReLU estimation/print interval
	gpu = true
	amp = true							# enabled only when gpu == true

	adv_train = 'nature' 				# ['nature', 'pgd', 'vae', 'gan', ...]


	# SDD: sampled dataset distribution
	# SAD: sampled adversarial distribution
	# NIP: naive interval propagation
	# SIP: symbolic interval propagation

[verify]
	time = 300
	memory = '8G'
	debug = true
	save_log = false
	
	# model selection strategy for verification
	# last(default): last epoch model
	#
	# For all below: must save intermediate models(save_intermediate = true)
	# best test accuracy: model with the best test accuracy
	# best relu accuracy: model with the most amount of stable relus
	# top [x] test accuaracy: model with the most amount of stable relus with [x]% accuarcy difference of the model with the best tests accuracy
	# top [x] relu accuaracy: model with the best test accuracy with [x]% stable relu difference of the model with the most amount of stable relus
	# target_model = 'last'
	target_model = 'best test accuracy of last 5 epochs'
