name = 'test'

[train]
	artifact = 'MNIST'
	network = 'NetS'
	epochs = 100
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.7 			# Learning rate step gamma
	save_model = true
	log_interval = 500		# pring while n-th batch
	gpu = true

	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]
	
	[train.dispatch]
		platform = "local"

[ReLU_estimation]	
	method = 'TD' # TD: train distribution, IP: interval propagation

[heuristic]


[verify]
	time = 600
	memory = '8G'
	debug = false
	[verify.verifiers]
		DNNV = ['eran_deepzono','neurify','planet','nnenum']

	[verify.dispatch]
		platform = "local"