name = 'test'

[train]
	artifact = 'MNIST'
	network = 'NetL'
	epochs = 100
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.7 			# Learning rate step gamma
	save_model = true
	log_interval = 500		# pring while n-th batch
	gpu = true

	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]
	
	[train.dispatch]
		platform = "local"

[ReLU_estimation]	
	method = 'TD' # TD: train distribution, IP: interval propagation

[heuristic]
	[heuristic.bias_shaping]
		mode = 'standard'
		intensity = 5e-2
		occurrence = 5e-3
		start = 25 			# inclusive
		end = 75 			# inclusive
	
	#[heuristic.rs_loss]
	#	mode = 'standard'
	#	weight = 1e-4
	#	epsilon = 1e-1
	#	start = 1
	#	end = 10

	#[heuristic.pruning]
	#	mode = 'structure'
	#	re_arch = 'standard'
	#	sparsity = 30
	#	start = 1
	#	end = 10



[verify]
	time = 600
	memory = '8G'
	debug = false
	[verify.verifiers]
		DNNV = ['eran_deepzono','neurify','planet','nnenum']

	[verify.dispatch]
		platform = "local"