name = 'test'

[train]
	artifact = 'MNIST'
	net_name = 'NetS'
	net_layers = [784, 128, 128, 128, 10]

	epochs = 10
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4				# learning rate
	gamma = 0.7 			# Learning rate step gamma
	save_model = true
	save_log = true
	log_interval = 500		# pring while n-th batch
	gpu = true

	ReLU_estimation = 'TD' # TD: train distribution, IP: interval propagation, VS: verification sampling
	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]	

[heuristic]
	[heuristic.bias_shaping]
		mode = 'standard'
		intensity = 5e-2
		occurrence = 5e-3
		start = 1			# inclusive
		end = 10 			# inclusive
	
	#[heuristic.rs_loss]
	#	mode = 'standard'
	#	weight = 1e-4
	#	epsilon = 1e-1
	#	start = 2
	#	end = 9

	#[heuristic.prune]
	#	mode = 'structure'
	#	re_arch = 'standard'
	#	sparsity = 30
	#	start = 2
	#	end = 9



[verify]
	time = 600
	memory = '8G'
	debug = false
	save_log = true

	property = 0
	epsilon = 0.02
	verifier = 'eran_deepzono'
