name = 'test'

[train]
	artifact = 'CIFAR10'
	net_name = 'CIFAR2020_2_255'

	epochs = 5
	batch_size = 16
	test_batch_size = 16
	lr = 1e-4							# learning rate
	gamma = 0.95 							# Learning rate decay
	save_model = true
	save_intermediate = true
	save_log = true
	gpu = true
	log_interval = 100					# Stable ReLU estimation/print interval
	amp = true							# enabled only when gpu == true

	adv_train = 'nature' 				# ['nature', 'pgd', 'vae', 'gan', ...]


	# SDD: sampled dataset distribution
	# SAD: sampled adversarial distribution
	# NIP: interval propagation

	[train.stable_estimators]
		[train.stable_estimators.SDD]
		
		#[train.stable_estimators.SAD]
		#	epsilon = 0.08

		#[train.stable_estimators.NIP]
		#	epsilon = 0.08
			
		#[train.stable_estimators.SIP]
		#	epsilon = 0.08
		
		#[train.stable_estimators.ALR]
		#	method = 'CROWN'
		#	epsilon = 0.08


[stabilizers]
	[stabilizers.bias_shaping]
		mode = 'standard'
		# interval scheduling
		intensity = 2e-2
		pace = 50
		#decay = 0.99
		
		start = 1 			# inclusive
		end = 25 			# inclusive
		[stabilizers.bias_shaping.stable_estimators]
			[stabilizers.bias_shaping.stable_estimators.SDD]

[verify]
	time = 600
	memory = '16G'
	property = 0
	epsilon = 0.001
	debug = true
	save_log = false
	verifier = 'abcrown'
	
	target_model = 'last'