name = 'test'

[train]
	artifact = 'MNIST'
	net_name = 'NetS'
	net_layers = [784, 128, 128, 128, 10]

	epochs = 2
	batch_size = 64
	test_batch_size = 1000
	lr = 1e-4							# learning rate
	gamma = 1 							# Learning rate decay
	save_model = true
	save_intermediate = true
	log_interval = 500					# Stable ReLU estimation/print interval
	gpu = true
	amp = true							# enabled only when gpu == true

	# TD: train distribution
	# VS: verification sampling
	# IP: interval propagation
	ReLU_estimation = 'TD'
	adv_train = 'nature' 				# ['nature', 'pgd', 'vae', 'gan', ...]


[heuristic]
	[heuristic.bias_shaping]
		ReLU_estimation = 'TD'
		mode = 'standard'
		intensity = 5e-2
		occurrence = 5e-3
		# decay = 0.98
		start = 1 			# inclusive
		end = 100 			# inclusive
	
	#[heuristic.rs_loss]
	#	ReLU_estimation = 'IP'
	#	mode = 'standard'
	#	weight = 1e-4
	#	epsilon = 1e-1
	#	start = 1
	#	end = 9

	#[heuristic.prune]
	#	mode = 'structure'
	#	re_arch = 'standard'
	#	sparsity = 30
	#	start = 2
	#	end = 9


[verify]
	time = 600
	memory = '8G'
	property = 0
	epsilon = 0.02
	save_log = true
	verifier = 'neurify'
