class Settings:
    timeout = 600
    fig_dir = "results_figs"

    verifier_order = [
        "DNNV:eran_deeppoly",
        "DNNV:nnenum",
        "DNNVWB:neurify",
        "DNNVWB:neurify",
        "DNNV:marabou",
    ]

    network_order = ["NetS", "NetM", "NetL", "FC6", "OVAL21_o"]

    heuristics_order = [
        # singletons
        "Baseline",
        "B_SDD",
        "B_SAD",
        "B_NIP",
        "B_SIP",
        "R_SDD",
        "R_SAD",
        "R_NIP",
        "R_SIP",
        "P_SDD",
        "P_SAD",
        "P_NIP",
        "P_SIP",
        # combinations
        "BR_SDD",
        "BR_SAD",
        "BR_NIP",
        "BR_SIP",
        "BP_SDD",
        "BP_SAD",
        "BP_NIP",
        "BP_SIP",
        "RP_SDD",
        "RP_SAD",
        "RP_NIP",
        "RP_SIP",
        "BRP_SDD",
        "BRP_SAD",
        "BRP_NIP",
        "BRP_SIP",
        # combinations2
        "NNN",
        "NNB",
        "NNR",
        "NNP",
        "NBN",
        "NBB",
        "NBR",
        "NBP",
        "NRN",
        "NRB",
        "NRR",
        "NRP",
        "NPN",
        "NPB",
        "NPR",
        "NPP",
        "BNN",
        "BNB",
        "BNR",
        "BNP",
        "BBN",
        "BBB",
        "BBR",
        "BBP",
        "BRN",
        "BRB",
        "BRR",
        "BRP",
        "BPN",
        "BPB",
        "BPR",
        "BPP",
        "RNN",
        "RNB",
        "RNR",
        "RNP",
        "RBN",
        "RBB",
        "RBR",
        "RBP",
        "RRN",
        "RRB",
        "RRR",
        "RRP",
        "RPN",
        "RPB",
        "RPR",
        "RPP",
        "PNN",
        "PNB",
        "PNR",
        "PNP",
        "PBN",
        "PBB",
        "PBR",
        "PBP",
        "PRN",
        "PRB",
        "PRR",
        "PRP",
        "PPN",
        "PPB",
        "PPR",
        "PPP",
    ]

    convert_names = {
        "Baseline": "Baseline",
        # no change
        "B_SDD": "B_SDD",
        "B_SAD": "B_SAD",
        "B_NIP": "B_NIP",
        "B_SIP": "B_SIP",
        "R_SDD": "R_SDD",
        "R_SAD": "R_SAD",
        "R_NIP": "R_NIP",
        "R_SIP": "R_SIP",
        "P_SDD": "P_SDD",
        "P_SAD": "P_SAD",
        "P_NIP": "P_NIP",
        "P_SIP": "P_SIP",
        # 2char to 1char
        "BS_SDD": "B_SDD",
        "BS_SAD": "B_SAD",
        "BS_NIP": "B_NIP",
        "BS_SIP": "B_SIP",
        "RS_SDD": "R_SDD",
        "RS_SAD": "R_SAD",
        "RS_NIP": "R_NIP",
        "RS_SIP": "R_SIP",
        "PR_SDD": "P_SDD",
        "PR_SAD": "P_SAD",
        "PR_NIP": "P_NIP",
        "PR_SIP": "P_SIP",
        # combinations
        "BR_SDD": "BR_SDD",
        "BR_SAD": "BR_SAD",
        "BR_NIP": "BR_NIP",
        "BR_SIP": "BR_SIP",
        "BP_SDD": "BP_SDD",
        "BP_SAD": "BP_SAD",
        "BP_NIP": "BP_NIP",
        "BP_SIP": "BP_SIP",
        "RP_SDD": "RP_SDD",
        "RP_SAD": "RP_SAD",
        "RP_NIP": "RP_NIP",
        "RP_SIP": "RP_SIP",
        "BRP_SDD": "BRP_SDD",
        "BRP_SAD": "BRP_SAD",
        "BRP_NIP": "BRP_NIP",
        "BRP_SIP": "BRP_SIP",
        # combinations2
        "BBB": "BBB",
        "BBR": "BBR",
        "BBP": "BBP",
        "BBN": "BBN",
        "BRB": "BRB",
        "BRR": "BRR",
        "BRP": "BRP",
        "BRN": "BRN",
        "BPB": "BPB",
        "BPR": "BPR",
        "BPP": "BPP",
        "BPN": "BPN",
        "BNB": "BNB",
        "BNR": "BNR",
        "BNP": "BNP",
        "BNN": "BNN",
        "RBB": "RBB",
        "RBR": "RBR",
        "RBP": "RBP",
        "RBN": "RBN",
        "RRB": "RRB",
        "RRR": "RRR",
        "RRP": "RRP",
        "RRN": "RRN",
        "RPB": "RPB",
        "RPR": "RPR",
        "RPP": "RPP",
        "RPN": "RPN",
        "RNB": "RNB",
        "RNR": "RNR",
        "RNP": "RNP",
        "RNN": "RNN",
        "PBB": "PBB",
        "PBR": "PBR",
        "PBP": "PBP",
        "PBN": "PBN",
        "PRB": "PRB",
        "PRR": "PRR",
        "PRP": "PRP",
        "PRN": "PRN",
        "PPB": "PPB",
        "PPR": "PPR",
        "PPP": "PPP",
        "PPN": "PPN",
        "PNB": "PNB",
        "PNR": "PNR",
        "PNP": "PNP",
        "PNN": "PNN",
        "NBB": "NBB",
        "NBR": "NBR",
        "NBP": "NBP",
        "NBN": "NBN",
        "NRB": "NRB",
        "NRR": "NRR",
        "NRP": "NRP",
        "NRN": "NRN",
        "NPB": "NPB",
        "NPR": "NPR",
        "NPP": "NPP",
        "NPN": "NPN",
        "NNB": "NNB",
        "NNR": "NNR",
        "NNP": "NNP",
        "NNN": "Baseline",
    }
