name = 'e2p2'

[train]
	epochs = 25
	batch_size = 8
	test_batch_size = 8
	lr = 1e-4				# learning rate
	gamma = 0.95 			# Learning rate decay
	save_model = true
	save_log = true
	save_intermediate = true
	log_interval = 100		# pring while n-th batch
	gpu = true
	amp = false
	
	adv_train = 'nature' # ['nature', 'pgd', 'vae', 'gan', ...]	

	[train.stable_estimator]
		[train.stable_estimator.SDD]
		
		[train.stable_estimator.SAD]
			epsilon = 0.1
			samples = 100

		[train.stable_estimator.NIP]
			epsilon = 0.1

		[train.stable_estimator.SIP]
			epsilon = 0.1

[verify]
	time = 600
	memory = '16G'
	save_log = false
	debug = true
	
	#target_model = 'last'
	target_model = 'best test accuracy of last 5 epochs'
	verifier = 'DNNVWB:neurify'
